import GaussianTilt.MomentMapBoundaryRegularityBernsteinEstimate

/-! # Actual cutoff maxima with logarithmic gradient drift -/
noncomputable section
open Matrix Filter Set
open scoped Topology BigOperators ContDiff
namespace GaussianTilt.MomentMapRegularity
open GaussianTilt.Letwin
variable {n : ℕ}

/-- The drift generated by the true logarithm is absorbed at the actual
cutoff maximum. Its square is controlled by the energy itself. -/
theorem bernstein_cutoff_bound_at_max {A : Matrix (Fin n) (Fin n) ℝ}
    (hA : A.PosSemidef) {η F : CoordinateSpace n → ℝ} {x : CoordinateSpace n}
    (hη : ContDiffAt ℝ 2 η x) (hF : ContDiffAt ℝ 2 F x) (g : CoordinateSpace n)
    {c C B₀ B₁ B₂ B₃ : ℝ} (hc : 0 < c) (hC : 0 ≤ C)
    (hB₀ : 0 ≤ B₀) (hB₁ : 0 ≤ B₁) (hB₂ : 0 ≤ B₂) (hB₃ : 0 ≤ B₃)
    (hηx : 0 < η x) (hηB : η x ≤ B₀) (hFx : 1 ≤ F x)
    (hLF : c * (F x)^2 ≤ linearizedMA A F x +
      2 * (g ⬝ᵥ (A *ᵥ coordinateGradient F x)) + C * (F x + 1))
    (hLη : -B₁ ≤ linearizedMA A η x)
    (hΓ : coordinateGradient η x ⬝ᵥ (A *ᵥ coordinateGradient η x) ≤ B₂)
    (hcross : (g ⬝ᵥ (A *ᵥ coordinateGradient η x))^2 ≤ B₃ * F x)
    (hmax : IsLocalMax (fun y => (η y)^2 * F y) x) :
    (η x)^2 * F x ≤ 2 * (2*B₀*B₁ + 6*B₂ + 2*C*B₀^2) / c + 16*B₃/c^2 := by
  have hFpos : 0 < F x := lt_of_lt_of_le zero_lt_one hFx
  have hAs : A.IsSymm := by
    simpa only [Matrix.IsSymm, Matrix.IsHermitian, Matrix.conjTranspose_eq_transpose_of_trivial]
      using hA.isHermitian
  have hnon := linearizedMA_nonpos_at_max hA ((hη.pow 2).mul hF) hmax
  rw [linearized_cutoff_energy_at_max hAs hη hF hηx.ne' hmax] at hnon
  have hstat := cutoff_energy_stationarity (hη.differentiableAt (by norm_num))
    (hF.differentiableAt (by norm_num)) hηx.ne' hmax
  let d := g ⬝ᵥ (A *ᵥ coordinateGradient η x)
  have hd : (η x)^2 * (2 * (g ⬝ᵥ (A *ᵥ coordinateGradient F x))) = -4 * η x * F x * d := by
    rw [hstat, Matrix.mulVec_smul, dotProduct_smul]
    dsimp [d]
    field_simp
    <;> ring
  have h1 := mul_le_mul_of_nonneg_left hLF (sq_nonneg (η x))
  have h2 := mul_le_mul_of_nonneg_left hLη (show 0 ≤ 2 * η x * F x by positivity)
  have h3 := mul_le_mul_of_nonneg_left hΓ (show 0 ≤ 6 * F x by positivity)
  have h4 := mul_le_mul_of_nonneg_right hηB (show 0 ≤ 2 * B₁ * F x by positivity)
  have h5 := mul_le_mul_of_nonneg_right (pow_le_pow_left₀ hηx.le hηB 2)
    (show 0 ≤ 2 * C * F x by positivity)
  have h6 : C * (F x + 1) ≤ 2 * C * F x := by nlinarith
  have h7 := mul_le_mul_of_nonneg_left h6 (sq_nonneg (η x))
  rw [mul_add, mul_add, hd] at h1
  let W := (η x)^2 * F x
  let K := 2*B₀*B₁ + 6*B₂ + 2*C*B₀^2
  have hw : c * W ≤ K - 4 * (η x * d) := by
    have hh : (c * W - K + 4 * (η x * d)) * F x ≤ 0 := by
      dsimp [W, K]
      nlinarith
    have hle := (mul_le_mul_right hFpos).mp (show
      (c * W - K + 4 * (η x * d)) * F x ≤ 0 * F x by simpa using hh)
    linarith
  have hW : 0 ≤ W := by dsimp [W]; positivity
  have hdsq : (-2 * (η x * d))^2 ≤ (c/2 * W) * (8*B₃/c) := by
    have hh := mul_le_mul_of_nonneg_left hcross (show 0 ≤ 4 * (η x)^2 by positivity)
    dsimp [W, d]
    convert hh using 1 <;> field_simp <;> ring
  have hy := twice_le_add_of_sq_le_mul (show 0 ≤ c/2 * W by positivity)
    (show 0 ≤ 8*B₃/c by positivity) hdsq
  have hh : c/2 * W ≤ K + 8*B₃/c := by linarith
  change W ≤ 2 * K / c + 16*B₃/c^2
  calc
    W ≤ (K + 8*B₃/c)/(c/2) := (le_div_iff₀ (half_pos hc)).mpr (by nlinarith)
    _ = _ := by field_simp; ring

/-- Actual compact maximization supplies the estimate on the whole patch. -/
theorem bernstein_cutoff_bound_on_compact
    {S : Set (CoordinateSpace n)} (hS : IsCompact S)
    {A : CoordinateSpace n → Matrix (Fin n) (Fin n) ℝ}
    {η F : CoordinateSpace n → ℝ} (hη : ContDiff ℝ 2 η) (hF : ContDiff ℝ 2 F)
    (g : CoordinateSpace n → CoordinateSpace n)
    (hAz : ∀ y ∈ interior S, (A y).PosSemidef)
    (hzero : ∀ y ∈ frontier S, η y = 0) (hηpos : ∀ y ∈ interior S, 0 < η y)
    {c C B₀ B₁ B₂ B₃ : ℝ} (hc : 0 < c) (hC : 0 ≤ C)
    (hB₀ : 0 ≤ B₀) (hB₁ : 0 ≤ B₁) (hB₂ : 0 ≤ B₂) (hB₃ : 0 ≤ B₃)
    (hηB : ∀ y ∈ interior S, η y ≤ B₀)
    (hLF : ∀ y ∈ interior S, c*(F y)^2 ≤ linearizedMA (A y) F y +
      2 * (g y ⬝ᵥ (A y *ᵥ coordinateGradient F y)) + C*(F y+1))
    (hLη : ∀ y ∈ interior S, -B₁ ≤ linearizedMA (A y) η y)
    (hΓ : ∀ y ∈ interior S, coordinateGradient η y ⬝ᵥ (A y *ᵥ coordinateGradient η y) ≤ B₂)
    (hcross : ∀ y ∈ interior S, (g y ⬝ᵥ (A y *ᵥ coordinateGradient η y))^2 ≤ B₃ * F y) :
    ∀ x ∈ S, (η x)^2*F x ≤ B₀^2 + 2*(2*B₀*B₁+6*B₂+2*C*B₀^2)/c + 16*B₃/c^2 := by
  intro x hx
  have hbound0 : 0 ≤ 2*(2*B₀*B₁+6*B₂+2*C*B₀^2)/c + 16*B₃/c^2 := by positivity
  by_cases hFx : (η x)^2*F x ≤ 0
  · exact hFx.trans (by positivity)
  have hFx : 0 < (η x)^2*F x := lt_of_not_ge hFx
  obtain ⟨z, hz, hmax⟩ := hS.exists_isMaxOn ⟨x, hx⟩ ((hη.continuous.pow 2).mul hF.continuous).continuousOn
  have hxz : (η x)^2*F x ≤ (η z)^2*F z := hmax hx
  have hzi : z ∈ interior S := by
    by_contra hnot
    have hzb : z ∈ frontier S := ⟨subset_closure hz, hnot⟩
    rw [hzero z hzb] at hxz
    norm_num at hxz
    exact hFx.not_ge hxz
  by_cases hlarge : 1 ≤ F z
  · have hb := bernstein_cutoff_bound_at_max (hAz z hzi) hη.contDiffAt hF.contDiffAt (g z)
      hc hC hB₀ hB₁ hB₂ hB₃ (hηpos z hzi) (hηB z hzi) hlarge (hLF z hzi)
      (hLη z hzi) (hΓ z hzi) (hcross z hzi)
      (hmax.isLocalMax (mem_interior_iff_mem_nhds.mp hzi))
    exact hxz.trans (by nlinarith [sq_nonneg B₀])
  · have hs := mul_le_mul_of_nonneg_left (show F z ≤ 1 from (lt_of_not_ge hlarge).le) (sq_nonneg (η z))
    have hsq := pow_le_pow_left₀ (hηpos z hzi).le (hηB z hzi) 2
    exact hxz.trans (by nlinarith)

end GaussianTilt.MomentMapRegularity
